import dbConnect from '@/lib/db';
import Participant from '@/models/Participant';
import { NextResponse } from 'next/server';

// Basic sanitization helper
const sanitize = (str: any) => {
    if (typeof str !== 'string') return '';
    return str.replace(/[^\w\s@.-]/gi, ''); // Remove special characters except common ones
};

export async function GET() {
    try {
        await dbConnect();
        // Return only necessary fields to reduce data exposure
        const participants = await Participant.find({}).select('-__v');
        return NextResponse.json({ success: true, data: participants });
    } catch (error: any) {
        console.error("Database Error:", error);
        return NextResponse.json({ success: false, message: "Internal Server Error" }, { status: 500 });
    }
}

export async function POST(request: Request) {
    try {
        await dbConnect();
        const body = await request.json();

        // Sanitize inputs
        const cleanBody = {
            name: sanitize(body.name),
            college: sanitize(body.college),
            academicYear: sanitize(body.academicYear),
            foodItem: sanitize(body.foodItem),
            whatsapp: body.whatsapp?.replace(/\D/g, ''), // Only numbers
            token: body.token // Tokens are generated by us, so reasonably safe, but could sanitize too
        };

        // Check availability
        const existingParticipant = await Participant.findOne({ token: cleanBody.token });

        if (existingParticipant) {
            return NextResponse.json({
                success: true,
                data: existingParticipant,
                message: 'Participant already exists'
            });
        }

        const participant = await Participant.create(cleanBody);
        return NextResponse.json({ success: true, data: participant }, { status: 201 });
    } catch (error: any) {
        console.error("Database Error:", error);
        return NextResponse.json({
            success: false,
            error: error instanceof Error ? error.message : "Registration Failed",
            details: error
        }, { status: 500 });
    }
}

export async function PATCH(request: Request) {
    try {
        await dbConnect();
        const body = await request.json();
        const { token, meal } = body;

        // Basic validation
        if (!token || !meal) {
            return NextResponse.json({ success: false, message: 'Invalid Request' }, { status: 400 });
        }

        const updateData: any = {};
        if (meal === 'lunch') updateData.lunch = true;
        if (meal === 'dinner') updateData.dinner = true;

        const participant = await Participant.findOneAndUpdate(
            { token: token },
            updateData,
            { new: true }
        ).select('-__v');

        if (!participant) {
            return NextResponse.json({ success: false, message: 'Participant not found' }, { status: 404 });
        }

        return NextResponse.json({ success: true, data: participant });

    } catch (error: any) {
        console.error("Database Error:", error);
        return NextResponse.json({ success: false, error: "Update Failed" }, { status: 500 });
    }
}
